

***    
*** BUILD OPTIONS
***

    * hardware options
    OPT_DISABLE_BG_LAYER=0
    OPT_DISABLE_SPRITES=0
   
	* cheats to test game
    * score is decimal format
	* all options must be zeroed for release
    OPT_START_SCORE=0
	OPT_SKIP_THANKS_SCREEN=0
	OPT_SKIP_TITLE_SCREEN=0
	OPT_SKIP_ICE_PACK_SCREEN=0
	OPT_SKIP_GAME_DEMO=0
	OPT_ONLY_ONE_LIFE=0
	* test mode: only first snobee is active
	OPT_ONLY_ONE_SNOBEE=0
	* make diamonds almost grouped
	OPT_ALMOST_GROUP_DIAMONDS=0
***
*** end of BUILD OPTIONS
***




* sound ordinals

    .equ  CREDIT_SND,         0x00
    .equ  EXTRA_LIFE_SND,     0x01

    
